name: Trigger auto deployment for provadevops

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/provadevops-AutoDeployTrigger-a6a0b379-efa2-4d4c-af2e-5c3d2a62f969.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerprovadevops.azurecr.io
          username: ${{ secrets.PROVADEVOPS_REGISTRY_USERNAME }}
          password: ${{ secrets.PROVADEVOPS_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerprovadevops.azurecr.io/provadevops:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PROVADEVOPS_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n provadevops -g rg-prova-devops --server containerprovadevops.azurecr.io --username  ${{ secrets.PROVADEVOPS_REGISTRY_USERNAME }} --password ${{ secrets.PROVADEVOPS_REGISTRY_PASSWORD }}
            az containerapp update -n provadevops -g rg-prova-devops --image containerprovadevops.azurecr.io/provadevops:${{ github.sha }}
